---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: kubeconform
        name: kubeconform (kustomize build)
        entry: .hooks/kubeconform.sh
        language: script
        pass_filenames: false
        always_run: true

      - id: kube-score
        name: kube-score (kustomize build)
        entry: .hooks/kube-score.sh
        language: script
        pass_filenames: false
        always_run: true
