---
apiVersion: gcp.platform.upbound.io/v1alpha1
kind: XGKE
metadata:
  name: gcp-gke
spec:
  parameters:
    id: gcp-gke
    # To set a custom region, specify availability zones in the XNetwork
    # for all subnets. If not set, the default region and zones are used.
    region: us-west2
    version: latest
    nodes:
      count: 1
      instanceType: n1-standard-4
  writeConnectionSecretToRef:
    name: gcp-gke-kubeconfig
    namespace: crossplane-system
