---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: virtual-management

resources:
  - ./namespace.yaml
  - ../../../stacks/virtual-cluster/helm-chart

patches:
  - target:
      kind: HelmChartInflationGenerator
    patch: |-
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: virtual-management
      releaseName: virtual-management
      namespace: virtual-management
