---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: vcluster
valuesInline:
  experimental:
    deploy:
      host:
        manifestsTemplate: |
          ---
          # Push the vCluster credentails to KubeZero ClusterSecretStore,
          # which will save it as a Secret in the KubeZero namespace to be used as an Argo CD cluster config
          # (just a secret with a specific label).
          # https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters
          apiVersion: external-secrets.io/v1alpha1
          kind: PushSecret
          metadata:
            name: argo-cd-{{ .Release.Name }}-credentials
            namespace: {{ .Release.Name }}
          spec:
            refreshInterval: 5m
            secretStoreRefs:
              - name: kubezero-management
                kind: ClusterSecretStore
            selector:
              secret:
                name: vc-{{ .Release.Name }}
            data:
              - match:
                  secretKey: name
                  remoteRef:
                    remoteKey: argo-cd-{{ .Release.Name }}-credentials
                    property: name
              - match:
                  secretKey: server
                  remoteRef:
                    remoteKey: argo-cd-{{ .Release.Name }}-credentials
                    property: server
              - match:
                  secretKey: config
                  remoteRef:
                    remoteKey: argo-cd-{{ .Release.Name }}-credentials
                    property: config
            template:
              engineVersion: v2
              data:
                name: {{ .Release.Name }}
                server: https://{{ .Release.Name }}.{{ .Release.Namespace }}.svc:443
                config: |
                  {
                    "tlsClientConfig": {
                      "insecure": false,
                      "caData": "{{ printf "{{ index . "certificate-authority" | b64enc }}" }}",
                      "certData": "{{ printf "{{ index . "client-certificate" | b64enc }}" }}",
                      "keyData": "{{ printf "{{ index . "client-key" | b64enc }}" }}",
                      "serverName": "{{ .Release.Name }}"
                    }
                  }
