---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../modules/vcluster/helm-chart

patches:
  - target:
      kind: HelmChartInflationGenerator
    path: ./helm-chart.yaml
