---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: management-

resources:
  - ../../../modules/gcp/gke/provider
  - ../../../modules/gcp/gke/cluster

patches:
  - path: patch-xgke.yaml
    target:
      kind: XGKE
      name: gcp-gke
