---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-worker

resources:
  - ../../../stacks/virtual-cluster/helm-chart

patches:
  - target:
      kind: HelmChartInflationGenerator
    patch: |-
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: cluster-worker
      releaseName: cluster-worker
      namespace: cluster-worker
