---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager
name: cert-manager
repo: https://charts.jetstack.io
version: v1.11.0
releaseName: cert-manager
namespace: cert-manager
IncludeCRDs: true
