apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../stacks/virtual-cluster/helm-chart

patches:
  - target:
      kind: HelmChartInflationGenerator
    patch: |-
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: dev
      releaseName: dev
      namespace: dev
