---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: azure-management
spec:
  description: Management EKS cluster resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://github.com/kubezero/kubezero
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-management
  annotations:
    argocd.argoproj.io/sync-wave: '100'
    argocd.argoproj.io/depends-on: azure-provider
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: azure-management
  source:
    repoURL: https://github.com/kubezero/kubezero
    path: registry/azure-management/infrastructure
    targetRevision: main
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-management-applications
  annotations:
    argocd.argoproj.io/sync-wave: '100'
    argocd.argoproj.io/depends-on: azure-provider
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: azure-management
  source:
    repoURL: https://github.com/kubezero/kubezero
    path: registry/azure-management/applications
    targetRevision: main
  destination:
    # NOTE: Change the name according to your cluster.
    name: azure-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
