---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubezero-management
spec:
  provider:
    kubernetes:
      remoteNamespace: kubezero
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: eso-kubezero-management
          namespace: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-kubezero-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-kubezero-management
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-kubezero-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eso-kubezero-management
subjects:
  - kind: ServiceAccount
    name: eso-kubezero-management
    namespace: external-secrets
