---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - ../../modules/external-secrets
  - ./cluster-secret-store.yaml

generators:
  - ../../modules/external-secrets/helm-chart
