---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-nginx
name: ingress-nginx
repo: https://kubernetes.github.io/ingress-nginx
version: 4.12.2
releaseName: ingress-nginx
namespace: ingress-nginx
valuesFile: helm-chart/values.yaml
