apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: management
  namespace: argo-cd
spec:
  description: Platform management via Crossplane
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argo-cd
spec:
  description: Platform infrastructure resources
