---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-vault-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-sso
    kind: SecretStore
  target:
    name: example-secret
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: my-app/database
        property: password
    - secretKey: api-key
      remoteRef:
        key: my-app/api
        property: key 