---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../modules/vault
  - ../../../modules/external-secrets
  - ./vault-secretstore.yaml
  - ./example-externalsecret.yaml 