apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: management

resources:
  - ../../../stacks/virtual-cluster/helm-chart

patches:
  - target:
      kind: HelmChartInflationGenerator
    patch: |-
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: cluster-management
      releaseName: cluster-management
      namespace: cluster-management
