---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vcluster-dev

resources:
  - namespace.yaml
  - ../../base

configMapGenerator:
  - literals:
      - ARGOCD_CLUSTER_SECRET_NAME=vcluster-dev-argo-cd-config
      - ARGOCD_CLUSTER_NAME=vcluster-dev
      - VCLUSTER_NAMESPACE=vcluster-dev
    name: vcluster-env-vars-cm

patchesJson6902:
  - target:
      kind: Role
      name: secret-writer
      group: rbac.authorization.k8s.io
      version: v1
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kubezero
  - target:
      kind: RoleBinding
      name: secret-writer-binding
      group: rbac.authorization.k8s.io
      version: v1
    patch: |-
      - op: add
        path: /subjects/0/namespace
        value: vcluster-dev
      - op: replace
        path: /metadata/namespace
        value: kubezero
