---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aws-management
spec:
  description: Management EKS cluster resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://github.com/kubezero/kubezero
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-management
  annotations:
    argocd.argoproj.io/sync-wave: '100'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aws-management
  source:
    repoURL: https://github.com/kubezero/kubezero
    path: registry/aws-management
    targetRevision: main
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-provider
  namespace: kubezero
  annotations:
    argocd.argoproj.io/sync-wave: '100'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aws-management
  source:
    repoURL: https://github.com/kubezero/kubezero
    path: registry/aws-management/provider
    targetRevision: main
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
