---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./infrastructure/namespace.yaml

generators:
  - ./infrastructure
  - ../../controller
  - ../../stacks/k8s-essentials/helm-chart
