---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: worker-

resources:
  - ../../../modules/azure/aks/provider
  - ../../../stacks/aks-cluster

patches:
  - path: patch-xaks.yaml
    target:
      kind: XAKS
      name: azure-aks
  # - path: patch-xnetwork.yaml
  #   target:
  #     kind: XNetwork
  #     name: aws-network
