---
apiVersion: azure.platform.upbound.io/v1alpha1
kind: XAKS
metadata:
  name: azure-aks
spec:
  parameters:
    providerConfigName: management-provider-azure
  writeConnectionSecretToRef:
    name: management-azure-aks-kubeconfig
    namespace: crossplane-system
