---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../modules/cert-manager/helm-chart
  - ../../../modules/external-dns/helm-chart
  - ../../../modules/external-secrets/helm-chart
