apiVersion: kubernetes.digitalocean.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: digitalocean-doks
spec:
  providerConfigRef:
    name: management-digitalocean-providerconfig
  writeConnectionSecretToRef:
    name: management-digitalocean-doks-kubeconfig
    namespace: kubezero
