name: CI

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'cli/**'
      - '.github/workflows/**'
  push:
    branches: [ main, master ]
    paths:
      - 'cli/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: cli/go.sum

      - name: Get dependencies
        working-directory: ./cli
        run: go mod download

      - name: Verify dependencies
        working-directory: ./cli
        run: go mod verify

      - name: Build
        working-directory: ./cli
        run: go build -v ./...

      - name: Run tests
        working-directory: ./cli
        run: go test -v ./...

      - name: Run go vet
        working-directory: ./cli
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: ./cli
        run: staticcheck ./...

      - name: Test build for multiple platforms
        working-directory: ./cli
        run: |
          GOOS=linux GOARCH=amd64 go build -o /tmp/kubezero-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -o /tmp/kubezero-darwin-amd64 .
          GOOS=windows GOARCH=amd64 go build -o /tmp/kubezero-windows-amd64.exe .
          echo "✅ All platforms build successfully"
